version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: green_taxi
      POSTGRES_DB: taxi_zones  
    volumes:
      - /workspaces/DEZoomCamp/data:/docker-entrypoint-initdb.d  # Mount a directory containing SQL scripts for database initialization

  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root